### ISSUE TITLE
Device picture missalignment

### ISSUE THREAD

**Issue by WoMec** [samilliken/openDCIM#786] opened 2016-06-20 15:45 UTC
I have problem with alignment of device pictures. It is alignment to top, and there is gap at bottom. Size of the gap is depending to height of device. Size of picture doesn't have any effect to the gap.
I'm running  version 4.2.

![miss-alignment](https://cloud.githubusercontent.com/assets/7909801/16200734/c36f57d4-370e-11e6-96fb-1836b4329670.PNG)

**Comment by wilpig** [comment] 2016-06-20 15:51
Not a bug, Your image has been scaled to fit the available slot while maintaining the height to width ratio for the source image to ensure that they don't get distorted upon display.

**Comment by samilliken** [comment] 2016-06-20 15:57
Did you use one picture for the entire U2-U14 area?  Where are the device boundaries in this example?

**Comment by WoMec** [comment] 2016-06-20 16:02
Wilpig:Yes, but when i resize only height of image (I stretch it to a height), nothing changes. For exmaple, when I set image of full-rack device (42U), it looks like this:
orignal:
![emc-vmax-front](https://cloud.githubusercontent.com/assets/7909801/16201192/bb4629fa-3710-11e6-84e0-0df79b2ca781.png)
in rack:
![01](https://cloud.githubusercontent.com/assets/7909801/16201215/d1b19f26-3710-11e6-95cc-ea3077fc388f.PNG)

Samilliken:
one device is in U1 (single U device - EMC XMS server)
second device is storrate itself - from U2 to U14

original picture for storrage:
![emc-xio-front](https://cloud.githubusercontent.com/assets/7909801/16201299/16a6fd06-3711-11e6-9d65-87e0e97739dd.PNG)

original picture for XMS server:
![emc-xms-front](https://cloud.githubusercontent.com/assets/7909801/16201326/2af8e4b8-3711-11e6-87e2-41d198a2cfa7.png)

**Comment by wilpig** [comment] 2016-06-20 16:04
Because it's a ratio shrink the width of your image about 5px and it will line up better.  It can't be helped without adding in massive distortion for other images.  If you chop 2px from either side of your large image it will line up better.

**Comment by samilliken** [comment] 2016-06-20 16:06
For a 13U image your ratio should be roughly 192:143 (W:H)

**Comment by WoMec** [comment] 2016-06-20 16:11
You are saying, that pictures are resized with fixed ratio to fit width. Correct? 
So why picture of 42U device is resized without fixed ratio to fit width and height of 13U space?

**Comment by samilliken** [comment] 2016-06-20 16:23
Your image is still bound by the parameters you gave it - when you give it an image of a 42U tall device but tell it to fit in 13U of space, of course it will look like crap.  Bottom line is, this isn't an issue - it's more of a question.  If you want a perfect alignment of your pictures, you'll have to edit them to fit the proper ratio.  Closing issue.

**Closed by samilliken** 2016-06-20 16:23 UTC

**Comment by WoMec** [comment] 2016-06-20 16:45
This is not about crapy looking images. Of course that 42U image will look bad in 13U space. This issue is about blank space - gap between devices ...

![01](https://cloud.githubusercontent.com/assets/7909801/16202682/fedd232a-3716-11e6-80f9-4f510a98af39.PNG)

This gap wasn't there before updating to 4.2

**Comment by wilpig** [comment] 2016-06-20 17:09
If you're that concerned here's the function

https://github.com/samilliken/openDCIM/blob/master/classes/Device.class.php#L1965

Find the problem.

**Comment by WoMec** [comment] 2016-06-20 17:44
you're calculating standart rack HxW ratio correctly, 1.75/19 inches. That is ratio 0.092105  
... but your slot in openDCIM has dimmensions 21 to 220 pixels, and that is ratio 0.095454 

there is a problem ... if I replace this part of code with new calculation

`// adjusted height = targetWidth * height:width ratio for 1u * height of device in U
			$targetHeight=$targetWidth*21/220*$this->Height;`

everything is showing correctly


If I didn't miss something, this is only change to fix this problem ....

**Comment by WoMec** [comment] 2016-06-20 17:49
![01](https://cloud.githubusercontent.com/assets/7909801/16204623/0f4415a8-3720-11e6-9943-d82bb8847394.PNG)
![02](https://cloud.githubusercontent.com/assets/7909801/16204625/104619f6-3720-11e6-8933-6b138049492a.PNG)

**Comment by WoMec** [comment] 2016-06-21 08:44
I see that you already edited the code .... you're welcome ;)
